THIS_STOP = 'THIS_STOP'
NEXT_STOP = 'NEXT_STOP'
END_STOP = 'END_STOP'
ROUTE_NUM = 'ROUTE_NUM'
ROUTE_NUM_TEXT = 'ROUTE_NUM_TEXT'
THIS_STOP_TEXT = 'THIS_STOP_TEXT'
NEXT_STOP_TEXT = 'NEXT_STOP_TEXT'
END_STOP_TEXT = 'END_STOP_TEXT'

LED_NUM = "_ledNum"
LED_INTERNAL = "_ledInternal"
LCD_TEXT = "_lcdText"
LED_SIDE = "_ledSide"

AFTERSTATION = 'AFTERSTATION'
BEFORESTATION = 'BEFORESTATION'
NOEVENT = 'NOEVENT'
ONSTATION = 'ONSTATION'

